#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exercise2
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CursoLinQ")]
	public partial class PruebaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertEmpleado(Empleado instance);
    partial void UpdateEmpleado(Empleado instance);
    partial void DeleteEmpleado(Empleado instance);
    partial void InsertAlumno(Alumno instance);
    partial void UpdateAlumno(Alumno instance);
    partial void DeleteAlumno(Alumno instance);
    #endregion
		
		public PruebaDataContext() : 
				base(global::Exercise2.Properties.Settings.Default.CursoLinQConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PruebaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PruebaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PruebaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PruebaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Empleado> Empleado
		{
			get
			{
				return this.GetTable<Empleado>();
			}
		}
		
		public System.Data.Linq.Table<Alumno> Alumno
		{
			get
			{
				return this.GetTable<Alumno>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Empleado")]
	public partial class Empleado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _cve_empleado;
		
		private string _nombre_empleado;
		
		private string _apepaterno_empleado;
		
		private string _apematerno_empleado;
		
		private System.Nullable<int> _edad_empleado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncve_empleadoChanging(int value);
    partial void Oncve_empleadoChanged();
    partial void Onnombre_empleadoChanging(string value);
    partial void Onnombre_empleadoChanged();
    partial void Onapepaterno_empleadoChanging(string value);
    partial void Onapepaterno_empleadoChanged();
    partial void Onapematerno_empleadoChanging(string value);
    partial void Onapematerno_empleadoChanged();
    partial void Onedad_empleadoChanging(System.Nullable<int> value);
    partial void Onedad_empleadoChanged();
    #endregion
		
		public Empleado()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cve_empleado", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int cve_empleado
		{
			get
			{
				return this._cve_empleado;
			}
			set
			{
				if ((this._cve_empleado != value))
				{
					this.Oncve_empleadoChanging(value);
					this.SendPropertyChanging();
					this._cve_empleado = value;
					this.SendPropertyChanged("cve_empleado");
					this.Oncve_empleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_empleado", DbType="VarChar(50)")]
		public string nombre_empleado
		{
			get
			{
				return this._nombre_empleado;
			}
			set
			{
				if ((this._nombre_empleado != value))
				{
					this.Onnombre_empleadoChanging(value);
					this.SendPropertyChanging();
					this._nombre_empleado = value;
					this.SendPropertyChanged("nombre_empleado");
					this.Onnombre_empleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apepaterno_empleado", DbType="VarChar(50)")]
		public string apepaterno_empleado
		{
			get
			{
				return this._apepaterno_empleado;
			}
			set
			{
				if ((this._apepaterno_empleado != value))
				{
					this.Onapepaterno_empleadoChanging(value);
					this.SendPropertyChanging();
					this._apepaterno_empleado = value;
					this.SendPropertyChanged("apepaterno_empleado");
					this.Onapepaterno_empleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apematerno_empleado", DbType="VarChar(50)")]
		public string apematerno_empleado
		{
			get
			{
				return this._apematerno_empleado;
			}
			set
			{
				if ((this._apematerno_empleado != value))
				{
					this.Onapematerno_empleadoChanging(value);
					this.SendPropertyChanging();
					this._apematerno_empleado = value;
					this.SendPropertyChanged("apematerno_empleado");
					this.Onapematerno_empleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_edad_empleado", DbType="Int")]
		public System.Nullable<int> edad_empleado
		{
			get
			{
				return this._edad_empleado;
			}
			set
			{
				if ((this._edad_empleado != value))
				{
					this.Onedad_empleadoChanging(value);
					this.SendPropertyChanging();
					this._edad_empleado = value;
					this.SendPropertyChanged("edad_empleado");
					this.Onedad_empleadoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Alumno")]
	public partial class Alumno : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _cve_alumno;
		
		private string _nombre_alumno;
		
		private string _apepaterno_alumno;
		
		private string _apematerno_alumno;
		
		private System.Nullable<int> _nota1_alumno;
		
		private System.Nullable<int> _nota2_alumno;
		
		private System.Nullable<int> _nota3_alumno;
		
		private System.Nullable<int> _nota4_alumno;
		
		private string _cursofavorito_alumno;
		
		private string _nivelacademico_alumno;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncve_alumnoChanging(int value);
    partial void Oncve_alumnoChanged();
    partial void Onnombre_alumnoChanging(string value);
    partial void Onnombre_alumnoChanged();
    partial void Onapepaterno_alumnoChanging(string value);
    partial void Onapepaterno_alumnoChanged();
    partial void Onapematerno_alumnoChanging(string value);
    partial void Onapematerno_alumnoChanged();
    partial void Onnota1_alumnoChanging(System.Nullable<int> value);
    partial void Onnota1_alumnoChanged();
    partial void Onnota2_alumnoChanging(System.Nullable<int> value);
    partial void Onnota2_alumnoChanged();
    partial void Onnota3_alumnoChanging(System.Nullable<int> value);
    partial void Onnota3_alumnoChanged();
    partial void Onnota4_alumnoChanging(System.Nullable<int> value);
    partial void Onnota4_alumnoChanged();
    partial void Oncursofavorito_alumnoChanging(string value);
    partial void Oncursofavorito_alumnoChanged();
    partial void Onnivelacademico_alumnoChanging(string value);
    partial void Onnivelacademico_alumnoChanged();
    #endregion
		
		public Alumno()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cve_alumno", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int cve_alumno
		{
			get
			{
				return this._cve_alumno;
			}
			set
			{
				if ((this._cve_alumno != value))
				{
					this.Oncve_alumnoChanging(value);
					this.SendPropertyChanging();
					this._cve_alumno = value;
					this.SendPropertyChanged("cve_alumno");
					this.Oncve_alumnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_alumno", DbType="VarChar(50)")]
		public string nombre_alumno
		{
			get
			{
				return this._nombre_alumno;
			}
			set
			{
				if ((this._nombre_alumno != value))
				{
					this.Onnombre_alumnoChanging(value);
					this.SendPropertyChanging();
					this._nombre_alumno = value;
					this.SendPropertyChanged("nombre_alumno");
					this.Onnombre_alumnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apepaterno_alumno", DbType="VarChar(100)")]
		public string apepaterno_alumno
		{
			get
			{
				return this._apepaterno_alumno;
			}
			set
			{
				if ((this._apepaterno_alumno != value))
				{
					this.Onapepaterno_alumnoChanging(value);
					this.SendPropertyChanging();
					this._apepaterno_alumno = value;
					this.SendPropertyChanged("apepaterno_alumno");
					this.Onapepaterno_alumnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apematerno_alumno", DbType="VarChar(100)")]
		public string apematerno_alumno
		{
			get
			{
				return this._apematerno_alumno;
			}
			set
			{
				if ((this._apematerno_alumno != value))
				{
					this.Onapematerno_alumnoChanging(value);
					this.SendPropertyChanging();
					this._apematerno_alumno = value;
					this.SendPropertyChanged("apematerno_alumno");
					this.Onapematerno_alumnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nota1_alumno", DbType="Int")]
		public System.Nullable<int> nota1_alumno
		{
			get
			{
				return this._nota1_alumno;
			}
			set
			{
				if ((this._nota1_alumno != value))
				{
					this.Onnota1_alumnoChanging(value);
					this.SendPropertyChanging();
					this._nota1_alumno = value;
					this.SendPropertyChanged("nota1_alumno");
					this.Onnota1_alumnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nota2_alumno", DbType="Int")]
		public System.Nullable<int> nota2_alumno
		{
			get
			{
				return this._nota2_alumno;
			}
			set
			{
				if ((this._nota2_alumno != value))
				{
					this.Onnota2_alumnoChanging(value);
					this.SendPropertyChanging();
					this._nota2_alumno = value;
					this.SendPropertyChanged("nota2_alumno");
					this.Onnota2_alumnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nota3_alumno", DbType="Int")]
		public System.Nullable<int> nota3_alumno
		{
			get
			{
				return this._nota3_alumno;
			}
			set
			{
				if ((this._nota3_alumno != value))
				{
					this.Onnota3_alumnoChanging(value);
					this.SendPropertyChanging();
					this._nota3_alumno = value;
					this.SendPropertyChanged("nota3_alumno");
					this.Onnota3_alumnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nota4_alumno", DbType="Int")]
		public System.Nullable<int> nota4_alumno
		{
			get
			{
				return this._nota4_alumno;
			}
			set
			{
				if ((this._nota4_alumno != value))
				{
					this.Onnota4_alumnoChanging(value);
					this.SendPropertyChanging();
					this._nota4_alumno = value;
					this.SendPropertyChanged("nota4_alumno");
					this.Onnota4_alumnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cursofavorito_alumno", DbType="VarChar(100)")]
		public string cursofavorito_alumno
		{
			get
			{
				return this._cursofavorito_alumno;
			}
			set
			{
				if ((this._cursofavorito_alumno != value))
				{
					this.Oncursofavorito_alumnoChanging(value);
					this.SendPropertyChanging();
					this._cursofavorito_alumno = value;
					this.SendPropertyChanged("cursofavorito_alumno");
					this.Oncursofavorito_alumnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nivelacademico_alumno", DbType="VarChar(100)")]
		public string nivelacademico_alumno
		{
			get
			{
				return this._nivelacademico_alumno;
			}
			set
			{
				if ((this._nivelacademico_alumno != value))
				{
					this.Onnivelacademico_alumnoChanging(value);
					this.SendPropertyChanging();
					this._nivelacademico_alumno = value;
					this.SendPropertyChanged("nivelacademico_alumno");
					this.Onnivelacademico_alumnoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
